名字: Build
在:
工作流_调度:
输入:
包名:
描述: “游戏的包名:“
需要: 真实的

工作:
建设:
连续运行: Ubuntu-最新版
步伐:
    - 使用: 动作/签出@v3
    - 使用: 操作/设置-java@v3
随着:
分布: 特穆林
java版本: 11
隐藏物: 格拉德勒
    - 奔跑: |
chmod +x ./gradlew
sed-I‘s/module description =“/module description =“（$ { { github . event . inputs . package _ name } }）/g‘module . gradle
sed-I“s/com . game . package name/$ { { github . event . inputs . package _ name } }/g“module/src/main/CPP/game . h
。/gradlew:模块:程序集释放
    - 使用: 动作/上传-工件@v3
随着:
名字: zygisk-il2cppdumper
小路: out/magisk_module_release/
